In [56]:
#Kyan D.V. - 223400001
#MULTIPLE LINEAR REGRESSION
import pandas as pd
df = pd.read_excel('/content/HARGA RUMAH JAKSEL.xlsx')
df

            HARGA    LT   LB  JKT  JKM        GRS    KOTA
0     28000000000  1100  700    5    6        ADA  JAKSEL
1     19000000000   824  800    4    4        ADA  JAKSEL
2      4700000000   500  400    4    3        ADA  JAKSEL
3      4900000000   251  300    5    4        ADA  JAKSEL
4     28000000000  1340  575    4    5        ADA  JAKSEL
...           ...   ...  ...  ...  ...        ...     ...
996   16000000000   488  550    6    5        ADA  JAKSEL
997    4500000000   209  270    4    4        ADA  JAKSEL
998   29000000000   692  400    4    3  TIDAK ADA  JAKSEL
999    1700000000   102  140    4    3  TIDAK ADA  JAKSEL
1000   1250000000    63  110    3    3  TIDAK ADA  JAKSEL

[1001 rows x 7 columns]

In [44]:
df['KOTA'].value_counts()

KOTA
JAKSEL    1001
Name: count, dtype: int64

In [45]:
df['GRS'] = df['GRS'].map({'ADA': 1, 'TIDAK ADA': 0})
df

            HARGA    LT   LB  JKT  JKM  GRS    KOTA
0     28000000000  1100  700    5    6    1  JAKSEL
1     19000000000   824  800    4    4    1  JAKSEL
2      4700000000   500  400    4    3    1  JAKSEL
3      4900000000   251  300    5    4    1  JAKSEL
4     28000000000  1340  575    4    5    1  JAKSEL
...           ...   ...  ...  ...  ...  ...     ...
996   16000000000   488  550    6    5    1  JAKSEL
997    4500000000   209  270    4    4    1  JAKSEL
998   29000000000   692  400    4    3    0  JAKSEL
999    1700000000   102  140    4    3    0  JAKSEL
1000   1250000000    63  110    3    3    0  JAKSEL

[1001 rows x 7 columns]

In [28]:
df['GRS'].value_counts()

GRS
1    779
0    222
Name: count, dtype: int64

In [46]:
df['KOTA'] = df['KOTA'].map({'JAKSEL': 0})
df

            HARGA    LT   LB  JKT  JKM  GRS  KOTA
0     28000000000  1100  700    5    6    1     0
1     19000000000   824  800    4    4    1     0
2      4700000000   500  400    4    3    1     0
3      4900000000   251  300    5    4    1     0
4     28000000000  1340  575    4    5    1     0
...           ...   ...  ...  ...  ...  ...   ...
996   16000000000   488  550    6    5    1     0
997    4500000000   209  270    4    4    1     0
998   29000000000   692  400    4    3    0     0
999    1700000000   102  140    4    3    0     0
1000   1250000000    63  110    3    3    0     0

[1001 rows x 7 columns]

In [47]:
import statsmodels.api as sm
Y = df['HARGA']
X = df[['LT', 'LB', 'JKT', 'JKM', 'GRS', 'KOTA']]
X = sm.add_constant(X)

In [48]:
ks = sm.OLS(Y, X)
ks_res =ks.fit()
ks_res.summary()

/usr/local/lib/python3.10/dist-packages/statsmodels/regression/linear_model.py:1966: RuntimeWarning: divide by zero encountered in scalar divide
  return np.sqrt(eigvals[0]/eigvals[-1])

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  HARGA   R-squared:                       0.593
Model:                            OLS   Adj. R-squared:                  0.591
Method:                 Least Squares   F-statistic:                     289.4
Date:                Sat, 16 Nov 2024   Prob (F-statistic):          3.89e-191
Time:                        18:14:41   Log-Likelihood:                -24752.
No. Observations:                1001   AIC:                         4.952e+04
Df Residuals:                     995   BIC:                         4.955e+04
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.421e+09   1.29e+09     -2.647      0.008   -5.96e+09   -8.85e+08
LT          2.142e+07   1.09e+06     19.700      0.000    1.93e+07    2.35e+07
LB          1.218e+07   1.28e+06      9.526      0.000    9.67e+06    1.47e+07
JKT         1.659e+08   4.02e+08      0.413      0.680   -6.23e+08    9.55e+08
JKM         3.657e+08   4.26e+08      0.859      0.391    -4.7e+08     1.2e+09
GRS         1.825e+09   1.02e+09      1.790      0.074   -1.75e+08    3.83e+09
KOTA                0          0        nan        nan           0           0
==============================================================================
Omnibus:                      969.853   Durbin-Watson:                   1.624
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            59130.815
Skew:                           4.351   Prob(JB):                         0.00
Kurtosis:                      39.633   Cond. No.                          inf
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is      0. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [49]:
#POLYNOMIAL REGRESSION
import datetime as dt
import sys
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from math import sqrt

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

poly_reg = PolynomialFeatures(degree=2) # You can adjust the degree
X_poly_train = poly_reg.fit_transform(X_train)
X_poly_test = poly_reg.transform(X_test)

lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly_train, y_train)
y_pred_poly = lin_reg_2.predict(X_poly_test)

rmse_poly = sqrt(mean_squared_error(y_test, y_pred_poly))
mse_poly = mean_squared_error(y_test, y_pred_poly)
r2_poly = lin_reg_2.score(X_poly_test, y_test)


y_pred_mlr = ks_res.predict(X_test)
rmse_mlr = sqrt(mean_squared_error(y_test, y_pred_mlr))
mse_mlr = mean_squared_error(y_test, y_pred_mlr)
r2_mlr = ks_res.rsquared

print("Multiple Linear Regression:")
print(f"R-squared: {r2_mlr}")
print(f"RMSE: {rmse_mlr}")
print(f"MSE: {mse_mlr}")

print("\nPolynomial Regression:")
print(f"R-squared: {r2_poly}")
print(f"RMSE: {rmse_poly}")
print(f"MSE: {mse_poly}")

Multiple Linear Regression:
R-squared: 0.5925593134440169
RMSE: 8511116020.235831
MSE: 7.243909590991502e+19

Polynomial Regression:
R-squared: 0.41277065547439284
RMSE: 9352097086.462294
MSE: 8.74617199146165e+19